language: python
sudo: false
python:
  - "2.6"
  - "2.7"
env:
  - KOTTI_TEST_DB_STRING=postgresql://postgres@localhost:5432/kotti_testing
  - KOTTI_TEST_DB_STRING=mysql+oursql://root@localhost:3306/kotti_testing
  - KOTTI_TEST_DB_STRING=sqlite://
install:
  - travis_retry pip install "pip==1.3.1"  # fix issue with fanstatic==1.0a
  - travis_retry pip install -e . -r requirements.txt --use-mirrors
  - pip uninstall -y Kotti
  - python setup.py develop
  - python setup.py dev
  - travis_retry pip install psycopg2 oursql python-coveralls
before_script:
  - psql -c 'create database kotti_testing;' -U postgres
  - mysql -e 'create database kotti_testing;'
script:
  - py.test --runslow --tb=native --cov=kotti --cov-report=term-missing
after_success:
  - coveralls
notifications:
  irc: "irc.freenode.org#kotti"
  email: false
